### ISSUE TITLE
Support for short path syntax

### ISSUE THREAD

**Issue by pepelsbey** [t32k/grunt-csso#17]
If you want to write optimised output to the same file you have to specify the same path twice. It happens when it’s not a source file and generated by a preprocessor:
```
csso: {
	task: {
		files: {
			'styles/screen.css': 'styles/screen.css'
		}
	}
},
```
But in [grunt-autoprefixer](https://github.com/nDmitry/grunt-autoprefixer) it’s possible to use `src` shortcut for such cases:
```
autoprefixer: {
	task: {
		src: 'styles/screen.css'
	}
}
```
But when I try to use the notation for grunt-csso, I see following error:
```
grunt csso
Running "csso:task" (csso) task
Warning: Unable to write "undefined" file (Error code: undefined)
```
Could you please implement support for the same shortcut? Thank you.

**Comment by t32k** [comment]
I published grunt-csso@0.7.0, so please use it. :)

**Comment by pepelsbey** [comment]
Thank you!

**Comment by t32k** [comment]
![寿司ゆき:ok_dish](https://d1zd1v0cxnbx2w.cloudfront.net/images/sets/sushiyuki/43.png)
