### ISSUE TITLE
Better error management

### ISSUE THREAD

**Issue by nitriques** [t32k/grunt-csso#25]
It would be cool to display the exception coming from csso.

I would change the following

```js
var proceed = csso.minify(original, { restructuring: options.restructuring, debug: options.debug });
```

to 

```js
var proceed;
try {
    proceed = csso.minify(original, { restructuring: options.restructuring, debug: options.debug });
}
catch (ex) {
   grunt.fail.fatal(ex.message + '  ' + ex.parseError.line);
   return;
}
if (proceed && proceed.length === 0) {
```

I was getting "Unexpected input" error but I would like to get the actual line where the error occurred.

**Comment by t32k** [comment]
Thanks!
https://github.com/t32k/grunt-csso/commit/5efa82b13d4ccb6867d0c621d4b7ca28be2e5a3d
