### ISSUE TITLE
peerDependencies causes error

### ISSUE THREAD

**Issue by andreasisaak** [t32k/grunt-csso#30]
Package version: 2.2.0

Affected node versions:
    - [x] 6.x

According to this ticket (https://github.com/gruntjs/grunt/issues/1537), your peerDependency to "grunt-cli": ">=1.0.0" create this error message :)

```
UNMET PEER DEPENDENCY grunt-cli@>=1.0.0
npm WARN grunt-csso@2.2.0 requires a peer of grunt-cli@>=1.0.0 but none was installed.
```

PS: Thanks for this grunt plugin, it works awesome!!!

**Comment by nitriques** [comment]
Hi @andreasisaak thanks for your feedback.

The warning you get is there as *a feature*. It yarns you that your do not have the grunt-cli package installed, which is required to run the plugin.

Doing `npm i grunt-cli -g` should make the warning go away.

You can read more on this here: http://npm.github.io/using-pkgs-docs/package-json/types/peerdependencies.html

Thanks again.

**Comment by andreasisaak** [comment]
Alright :) i will install the package

**Comment by nitriques** [comment]
Can you confirm that the issue's gone afterwards ? ;) Thanks

**Comment by andreasisaak** [comment]
No the error is still the same :(

**Comment by nitriques** [comment]
Does running `npm i && grunt` works ?

**Comment by andrewfleming** [comment]
I am getting this error also when running `npm install`.

node v8.1.4
npm 5.2.0

package.json include `"grunt-csso": "^2.2.0",`

```
npm list -g --depth=0
/usr/local/lib
├── grunt-cli@1.2.0
└── npm@5.2.0
```

When running grunt I get the following error:

Running "csso:build" (csso) task
Fatal error: Identifier is expected  (958)

**Comment by nitriques** [comment]
can you run `npm i grunt-csso` ?
It should save it into your package.json file and the `npm i` command will work.

```
$ npm i grunt-csso
npm WARN grunt-csso@2.2.0 requires a peer of grunt-cli@>=1.0.0 but none was installed.

+ grunt-csso@2.2.0
removed 41 packages and updated 2 packages in 7.767s

$ grunt --version
grunt-cli v1.2.0
grunt v1.0.1

$ npm i grunt-cli
+ grunt-cli@1.2.0
added 1 package in 3.309s

$ npm i grunt-csso
+ grunt-csso@2.2.0
updated 1 package in 3.221s
```

**Comment by nitriques** [comment]
Here's the problem with having things installed globally https://www.sitepoint.com/solve-global-npm-module-dependency-problem/
